### ISSUE TITLE
fracciones

### ISSUE THREAD

**Issue by RafaelOrtegaRios** [cursos-0-fc-ugr/Matematicas#1]
En las operaciones con fracciones creo que los casos más difíciles para los estudiantes  son aquellos en que hay más de una raya, porque no reparan en que hay una raya principal. Hay algo sobre eso en el ejercicio 1 pero yo propondría un ejercicio 2:
Calcula
 2
---- =
 4
----
 2

y

 2
----
 4
---- =
 2

Creo que mis alumnos lo entienden mejor cuando les hago notar que la división es una operación no asociativa.

**Comment by pedritomelenas** [comment]
Gracias, propuestos nuevos ejercicios que contemplan este ejemplo en 22f5774fe849e5307b15d07fd4dd8c9f30572911
