### ISSUE TITLE
radicales

### ISSUE THREAD

**Issue by RafaelOrtegaRios** [cursos-0-fc-ugr/Matematicas#2]
En la definición de radicales hay una errata        ...implica que...
Los principiantes suelen ser demasiado rápidos simplificando raíz y potencia, propongo un ejercicio 3:
¿se cumple siempre la identidad raíz cúbica (x^3)=x? ¿y raíz cuadrada (x^2)=x?

**Comment by pedritomelenas** [comment]
Gracias @RafaelOrtegaRios , arreglado en 22f5774fe849e5307b15d07fd4dd8c9f30572911.
