### ISSUE TITLE
extremos sin derivada segunda

### ISSUE THREAD

**Issue by RafaelOrtegaRios** [cursos-0-fc-ugr/Matematicas#3]
Aplicaciones de la derivada. Extremos relativos
Muchas veces se obliga al estudiante a calcular la derivada segunda cuando ya sabe que hay un cambio de monotonía. Esto lleva a un trabajo innecesario y en ocasiones a una pérdida de información. Propondría incluir algo del tipo: un segundo método para decidir la existencia de un extremo relativo consiste en observar un cambio de monotonía: la función pasa de creciente a decreciente (máximo) o de decreciente a creciente (mínimo).
También un ejercicio del tipo: calcula los extremos relativos de f(x)=x^4+7

**Comment by pedritomelenas** [comment]
@RafaelOrtegaRios , gracias. Resuelto en 0d2a6714fdba26f5a280160e3bbed05432a425cf
