### ISSUE TITLE
Conocimientos previos

### ISSUE THREAD

**Issue by jeroal** [cursos-0-fc-ugr/Matematicas#7]
Algunos conceptos que aparecen no tengo claro si los conocen los alumnos. Supongo que alguno irá más apareciendo. Los dejo por aquí por si alguno sabe decirme si son conocidos por los alumnos de bachillerato. 

En concreto, no tengo claro si conocen: cuerpo, anillo o grupo (abeliano)

**Comment by pedritomelenas** [comment]
Quito los nombres y dejo las propiedades.
Gracias

**Comment by pedritomelenas** [comment]
Para matrices, supuestamente arreglado con ece5b9cac29171a87192454e74e19675b0845edc
Si no encontráis otro sitio donde se haga referencia a grupos o anillos, cerramos.
