### ISSUE TITLE
Conjugado del complejo: falta definición

### ISSUE THREAD

**Issue by daniel-diaz-ucl** [cursos-0-fc-ugr/Matematicas#8]
En la página: https://cursos-0-fc-ugr.github.io/Matematicas/00-complejos.html falta la definición del conjugado del complejo. Se mencionan las propiedades después, pero la definición está cortada, incompleta.

**Comment by daniel-diaz-ucl** [comment]
https://cursos-0-fc-ugr.github.io/Matematicas/00-complejos.html Pregunta 6 del cuestionario final no tiene enunciado, sólo las respuestas.

**Comment by pedritomelenas** [comment]
@daniel-diaz-ucl, gracias por detectar estos errores. Por favor, comprueba si se han corregido en https://github.com/cursos-0-fc-ugr/Matematicas/commit/afd31f3e86a96e92f4045057533e1ba693b76b7d

**Comment by daniel-diaz-ucl** [comment]
Perfecto, gracias por la prontitud.

**Comment by pedritomelenas** [comment]
Gracias a ti. Espero que encuentras más errores y nos informes de ello. 
Cierro.
